### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 3.

### ISSUE THREAD

**Issue by Happyprince65** [TalkUHulk/realworld-stylegan2-encoder#7]
having this unknown error. 
i used sample images as well and new images as well. but nothing is solving this issue

 python scripts/test.py --ckpt_encoder ./art_mobile_encoder_1024p --ckpt_decoder ./art_decoder_1024p --network e4e --platform openvino --align --images_path ./test_images --edit --edit_direction ./editings/smile.npy
stylegan2 generating...: 0it [00:00, ?it/s]/home/smartdev/realworld/./tools/common.py:86: DeprecationWarning: QUAD is deprecated and will be removed in Pillow 10 (2023-07-01). Use Transform.QUAD instead.
  img = img.transform((transform_size, transform_size), Image.QUAD, (quad + 0.5).flatten(), Image.BILINEAR)
/home/smartdev/realworld/./tools/common.py:86: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  img = img.transform((transform_size, transform_size), Image.QUAD, (quad + 0.5).flatten(), Image.BILINEAR)
stylegan2 generating...: 0it [00:01, ?it/s]
Traceback (most recent call last):
  File "/home/smartdev/realworld/scripts/test.py", line 404, in <module>
    test_openvino(args)
  File "/home/smartdev/realworld/scripts/test.py", line 172, in test_openvino
    res = exec_decoder.infer(inputs={decoder_input_blob: [dlatents]})
  File "ie_api.pyx", line 1080, in openvino.inference_engine.ie_api.ExecutableNetwork.infer
  File "ie_api.pyx", line 1431, in openvino.inference_engine.ie_api.InferRequest.infer
  File "ie_api.pyx", line 1452, in openvino.inference_engine.ie_api.InferRequest.infer
  File "ie_api.pyx", line 1581, in openvino.inference_engine.ie_api.InferRequest._fill_inputs
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 3.

**Comment by dn-bit** [comment]
same issue face during run openvivo's test case if you found any solution then kindly share with me .....

and how's the first torch model works because there isn't ant best_model file given there

**Comment by TalkUHulk** [comment]
> same issue face during run openvivo's test case if you found any solution then kindly share with me .....
> 
> and how's the first torch model works because there isn't ant best_model file given there

openvino version: 2021.4

**Comment by TalkUHulk** [comment]
In the future, I will add all models to [ai.deploy.box](https://github.com/TalkUHulk/ai.deploy.box)
